#!/bin/bash


./gnu2sigma_with_cellsize_nm.pl table0.dat > data_0.dat
./gnu2sigma_with_cellsize_nm.pl table1.dat > data_1.dat
./gnu2sigma_with_cellsize_nm.pl table2.dat > data_2.dat
./gnu2sigma_with_cellsize_nm.pl table3.dat > data_3.dat
./gnu2sigma_with_cellsize_nm.pl table4.dat > data_4.dat
./gnu2sigma_with_cellsize_nm.pl table5.dat > data_5.dat
./gnu2sigma_with_cellsize_nm.pl table6.dat > data_6.dat
./gnu2sigma_with_cellsize_nm.pl table7.dat > data_7.dat
./gnu2sigma_with_cellsize_nm.pl table8.dat > data_8.dat
./gnu2sigma_with_cellsize_nm.pl table9.dat > data_9.dat
./gnu2sigma_with_cellsize_nm.pl table10.dat > data_10.dat
./gnu2sigma_with_cellsize_nm.pl table11.dat > data_11.dat
./gnu2sigma_with_cellsize_nm.pl table12.dat > data_12.dat
./gnu2sigma_with_cellsize_nm.pl table13.dat > data_13.dat
./gnu2sigma_with_cellsize_nm.pl table14.dat > data_14.dat
./gnu2sigma_with_cellsize_nm.pl table15.dat > data_15.dat
./gnu2sigma_with_cellsize_nm.pl table16.dat > data_16.dat
./gnu2sigma_with_cellsize_nm.pl table17.dat > data_17.dat
./gnu2sigma_with_cellsize_nm.pl table18.dat > data_18.dat
./gnu2sigma_with_cellsize_nm.pl table19.dat > data_19.dat
./gnu2sigma_with_cellsize_nm.pl table20.dat > data_20.dat
./gnu2sigma_with_cellsize_nm.pl table21.dat > data_21.dat
./gnu2sigma_with_cellsize_nm.pl table22.dat > data_22.dat
./gnu2sigma_with_cellsize_nm.pl table23.dat > data_23.dat
./gnu2sigma_with_cellsize_nm.pl table24.dat > data_24.dat
./gnu2sigma_with_cellsize_nm.pl table25.dat > data_25.dat
./gnu2sigma_with_cellsize_nm.pl table26.dat > data_26.dat
./gnu2sigma_with_cellsize_nm.pl table27.dat > data_27.dat
./gnu2sigma_with_cellsize_nm.pl table28.dat > data_28.dat
./gnu2sigma_with_cellsize_nm.pl table29.dat > data_29.dat
./gnu2sigma_with_cellsize_nm.pl table30.dat > data_30.dat
./gnu2sigma_with_cellsize_nm.pl table31.dat > data_31.dat
./gnu2sigma_with_cellsize_nm.pl table32.dat > data_32.dat
./gnu2sigma_with_cellsize_nm.pl table33.dat > data_33.dat
./gnu2sigma_with_cellsize_nm.pl table34.dat > data_34.dat
./gnu2sigma_with_cellsize_nm.pl table35.dat > data_35.dat
./gnu2sigma_with_cellsize_nm.pl table36.dat > data_36.dat
./gnu2sigma_with_cellsize_nm.pl table37.dat > data_37.dat
./gnu2sigma_with_cellsize_nm.pl table38.dat > data_38.dat
./gnu2sigma_with_cellsize_nm.pl table39.dat > data_39.dat
./gnu2sigma_with_cellsize_nm.pl table40.dat > data_40.dat
./gnu2sigma_with_cellsize_nm.pl table41.dat > data_41.dat
./gnu2sigma_with_cellsize_nm.pl table42.dat > data_42.dat
./gnu2sigma_with_cellsize_nm.pl table43.dat > data_43.dat
./gnu2sigma_with_cellsize_nm.pl table44.dat > data_44.dat
./gnu2sigma_with_cellsize_nm.pl table45.dat > data_45.dat
./gnu2sigma_with_cellsize_nm.pl table46.dat > data_46.dat
./gnu2sigma_with_cellsize_nm.pl table47.dat > data_47.dat
./gnu2sigma_with_cellsize_nm.pl table48.dat > data_48.dat
./gnu2sigma_with_cellsize_nm.pl table49.dat > data_49.dat
./gnu2sigma_with_cellsize_nm.pl table50.dat > data_50.dat
./gnu2sigma_with_cellsize_nm.pl table51.dat > data_51.dat
./gnu2sigma_with_cellsize_nm.pl table52.dat > data_52.dat
./gnu2sigma_with_cellsize_nm.pl table53.dat > data_53.dat
./gnu2sigma_with_cellsize_nm.pl table54.dat > data_54.dat
./gnu2sigma_with_cellsize_nm.pl table55.dat > data_55.dat
./gnu2sigma_with_cellsize_nm.pl table56.dat > data_56.dat
./gnu2sigma_with_cellsize_nm.pl table57.dat > data_57.dat
./gnu2sigma_with_cellsize_nm.pl table58.dat > data_58.dat
./gnu2sigma_with_cellsize_nm.pl table59.dat > data_59.dat
./gnu2sigma_with_cellsize_nm.pl table60.dat > data_60.dat
./gnu2sigma_with_cellsize_nm.pl table61.dat > data_61.dat
./gnu2sigma_with_cellsize_nm.pl table62.dat > data_62.dat
./gnu2sigma_with_cellsize_nm.pl table63.dat > data_63.dat
./gnu2sigma_with_cellsize_nm.pl table64.dat > data_64.dat
./gnu2sigma_with_cellsize_nm.pl table65.dat > data_65.dat
./gnu2sigma_with_cellsize_nm.pl table66.dat > data_66.dat
./gnu2sigma_with_cellsize_nm.pl table67.dat > data_67.dat
./gnu2sigma_with_cellsize_nm.pl table68.dat > data_68.dat
./gnu2sigma_with_cellsize_nm.pl table69.dat > data_69.dat
./gnu2sigma_with_cellsize_nm.pl table70.dat > data_70.dat
./gnu2sigma_with_cellsize_nm.pl table71.dat > data_71.dat
./gnu2sigma_with_cellsize_nm.pl table72.dat > data_72.dat
./gnu2sigma_with_cellsize_nm.pl table73.dat > data_73.dat
./gnu2sigma_with_cellsize_nm.pl table74.dat > data_74.dat
./gnu2sigma_with_cellsize_nm.pl table75.dat > data_75.dat
./gnu2sigma_with_cellsize_nm.pl table76.dat > data_76.dat
./gnu2sigma_with_cellsize_nm.pl table77.dat > data_77.dat
./gnu2sigma_with_cellsize_nm.pl table78.dat > data_78.dat
./gnu2sigma_with_cellsize_nm.pl table79.dat > data_79.dat
./gnu2sigma_with_cellsize_nm.pl table80.dat > data_80.dat
./gnu2sigma_with_cellsize_nm.pl table81.dat > data_81.dat
./gnu2sigma_with_cellsize_nm.pl table82.dat > data_82.dat
./gnu2sigma_with_cellsize_nm.pl table83.dat > data_83.dat
./gnu2sigma_with_cellsize_nm.pl table84.dat > data_84.dat
./gnu2sigma_with_cellsize_nm.pl table85.dat > data_85.dat
./gnu2sigma_with_cellsize_nm.pl table86.dat > data_86.dat
./gnu2sigma_with_cellsize_nm.pl table87.dat > data_87.dat
./gnu2sigma_with_cellsize_nm.pl table88.dat > data_88.dat
./gnu2sigma_with_cellsize_nm.pl table89.dat > data_89.dat
./gnu2sigma_with_cellsize_nm.pl table90.dat > data_90.dat
./gnu2sigma_with_cellsize_nm.pl table91.dat > data_91.dat
./gnu2sigma_with_cellsize_nm.pl table92.dat > data_92.dat
./gnu2sigma_with_cellsize_nm.pl table93.dat > data_93.dat
./gnu2sigma_with_cellsize_nm.pl table94.dat > data_94.dat
./gnu2sigma_with_cellsize_nm.pl table95.dat > data_95.dat
./gnu2sigma_with_cellsize_nm.pl table96.dat > data_96.dat
./gnu2sigma_with_cellsize_nm.pl table97.dat > data_97.dat
./gnu2sigma_with_cellsize_nm.pl table98.dat > data_98.dat
./gnu2sigma_with_cellsize_nm.pl table99.dat > data_99.dat
./gnu2sigma_with_cellsize_nm.pl table100.dat > data_100.dat



